version: "3"

services:
  db:
    image: postgres
    container_name: go-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
    networks:
      - app-networks-pg
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "wesleypassos601@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - app-networks-pg

networks:
  app-networks-pg:
    driver: bridge